# Model Preferences

In [31]:
import pandas as pd

from build_model import get_instance
from non_dominated_surface import load_non_dominated_surface
from simulate_preference import preferences, convert_examples, simulate_preferences

In [32]:
instance = get_instance("medium_instance.json")
surface = load_non_dominated_surface("medium_instance.pkl")

## With preferences given by the user

In [33]:
ex = pd.DataFrame(
        {
            "objVal": [400, 350, 210, 220, 370, 360],
            "max_assigned": [8, 7, 2, 2, 4, 3],
            "max_duration": [3, 2, 10, 12, 9, 8],
            "status": [
                "unacceptable",
                "unacceptable",
                "correct",
                "correct",
                "satisfactory",
                "satisfactory",
            ],
        }
    )
ex

   objVal  max_assigned  max_duration        status
0     400             8             3  unacceptable
1     350             7             2  unacceptable
2     210             2            10       correct
3     220             2            12       correct
4     370             4             9  satisfactory
5     360             3             8  satisfactory

In [34]:
unacceptable, correct, satisfactory = convert_examples(ex, instance)
preferences(instance, surface, unacceptable, correct, satisfactory)

Gurobi Optimizer version 10.0.0 build v10.0.0rc2 (linux64)

CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 9 rows, 6 columns and 43 nonzeros
Model fingerprint: 0x9a53d421
Coefficient statistics:
  Matrix range     [4e-01, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve time: 0.01s
Presolved: 9 rows, 6 columns, 43 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.0000000e+00   8.039216e+00   0.000000e+00      0s
       6    2.8322440e-02   0.000000e+00   0.000000e+00      0s

Solved in 6 iterations and 0.02 seconds (0.00 work units)
Optimal objective  2.832244009e-02
Weights:	(0.44, 0.56, 0.00)
Thresholds:	(0.64, 0.70)

     objVal  max_assigned  max_duration     score        status
2   381.973             3            12  0.777319  satisfactory
7   381.973             3            12  0.777319  satisfactory
19  378.976             3             9  0.774707  satisfactory
25  378.976             3             9  0.774707  satisfactory
13  378.975             3            10  0.774706  satisfactory
..      ...           ...           ...       ...           ...
67   79.992             1             3  0.588228  unacceptable
63  249.972             5             3  0.588211  unacceptable
62  264.967             6             3  0.564241  unacceptable
69   -0.000             0             0  0.555556  unacceptable
68   29.993             1             2  0.544656  unacceptable

[70 rows x 5 columns]

## With simulated preferences

In [35]:
unacceptable, correct, satisfactory = simulate_preferences(instance, surface, sample_freq=0.3)
preferences(instance, surface, unacceptable, correct, satisfactory)

Simulated weights:	(0.23, 0.36, 0.41)
Simulated thresholds:	(0.69, 0.75)
Gurobi Optimizer version 10.0.0 build v10.0.0rc2 (linux64)

CPU model: AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 31 rows, 6 columns and 153 nonzeros
Model fingerprint: 0x0892cde1
Coefficient statistics:
  Matrix range     [2e-01, 1e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 5 rows and 0 columns
Presolve time: 0.01s
Presolved: 26 rows, 6 columns, 128 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.0000000e+00   2.832127e+01   0.000000e+00      0s
       8    1.1220376e-02   0.000000e+00   0.000000e+00      0s

Solved in 8 iterations and 0.02 seconds (0.00 work units)
Optimal objective  1.122037624e-02
Weights:	(0.25, 0.37, 0.38)
Thresholds:	(0.69, 0.74)

     objVal  max_assigned  max_duration     score        status
69   -0.000             0             0  0.750447  satisfactory
52  321.980             3             5  0.747511  satisfactory
58  330.976             4             4  0.744629  satisfactory
51  364.975             4             5  0.743936  satisfactory
59  278.981             3             4  0.743800  satisfactory
..      ...           ...           ...       ...           ...
0   412.964             5            11  0.638828  unacceptable
11  412.964             5            11  0.638828  unacceptable
16  412.960             6            10  0.631542  unacceptable
9   193.983             1            12  0.612798  unacceptable
4   193.982             1            13  0.595468  unacceptable

[70 rows x 5 columns]